//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagroom.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Instagroom.Core.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        public static string Login_UserNamePlaceholder {
            get {
                return ResourceManager.GetString("Login_UserNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        public static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login_SignUp", resourceCulture);
            }
        }
        
        public static string Login_ConnectWith {
            get {
                return ResourceManager.GetString("Login_ConnectWith", resourceCulture);
            }
        }
        
        public static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp_Email", resourceCulture);
            }
        }
        
        public static string SignUp_EmailPlaceholder {
            get {
                return ResourceManager.GetString("SignUp_EmailPlaceholder", resourceCulture);
            }
        }
        
        public static string SignUp_FirstName {
            get {
                return ResourceManager.GetString("SignUp_FirstName", resourceCulture);
            }
        }
        
        public static string SignUp_FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("SignUp_FirstNamePlaceholder", resourceCulture);
            }
        }
        
        public static string SignUp_LastName {
            get {
                return ResourceManager.GetString("SignUp_LastName", resourceCulture);
            }
        }
        
        public static string SignUp_LastNamePlaceholder {
            get {
                return ResourceManager.GetString("SignUp_LastNamePlaceholder", resourceCulture);
            }
        }
        
        public static string SignUp_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("SignUp_PasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string SignUp_PasswordConfirmation {
            get {
                return ResourceManager.GetString("SignUp_PasswordConfirmation", resourceCulture);
            }
        }
        
        public static string SignUp_PasswordConfirmationPlaceholder {
            get {
                return ResourceManager.GetString("SignUp_PasswordConfirmationPlaceholder", resourceCulture);
            }
        }
        
        public static string SignUp_Cancel {
            get {
                return ResourceManager.GetString("SignUp_Cancel", resourceCulture);
            }
        }
        
        public static string Message_WrongPassword {
            get {
                return ResourceManager.GetString("Message_WrongPassword", resourceCulture);
            }
        }
        
        public static string Message_EmptyPassword {
            get {
                return ResourceManager.GetString("Message_EmptyPassword", resourceCulture);
            }
        }
        
        public static string Message_WrongUserPassword {
            get {
                return ResourceManager.GetString("Message_WrongUserPassword", resourceCulture);
            }
        }
        
        public static string Message_WrongEmail {
            get {
                return ResourceManager.GetString("Message_WrongEmail", resourceCulture);
            }
        }
        
        public static string Message_EmptyEmail {
            get {
                return ResourceManager.GetString("Message_EmptyEmail", resourceCulture);
            }
        }
        
        public static string Message_WrongPasswordConfirmation {
            get {
                return ResourceManager.GetString("Message_WrongPasswordConfirmation", resourceCulture);
            }
        }
        
        public static string Message_EmptyFirstName {
            get {
                return ResourceManager.GetString("Message_EmptyFirstName", resourceCulture);
            }
        }
        
        public static string Message_EmptyLastName {
            get {
                return ResourceManager.GetString("Message_EmptyLastName", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        public static string NoSuchUserExists {
            get {
                return ResourceManager.GetString("NoSuchUserExists", resourceCulture);
            }
        }
    }
}
